<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="LAPTOP-UEEMDNDB" ignored="3" tests="0" failures="0" timestamp="17 Aug 2018 11:24:48 GMT" time="0.002" errors="0">
  <testcase name="successGetCall" time="0.0" classname="com.project.api.testscenarios.functionalvalidationtests.CustomerOnboarding_GetCall">
    <ignored/>
  </testcase> <!-- successGetCall -->
  <testcase name="testGetCallForInvalidCustomerId" time="0.0" classname="com.project.api.testscenarios.functionalvalidationtests.CustomerOnboarding_GetCall">
    <ignored/>
  </testcase> <!-- testGetCallForInvalidCustomerId -->
  <testcase name="testGetCallWithInvalidUrl" time="0.0" classname="com.project.api.testscenarios.functionalvalidationtests.CustomerOnboarding_GetCall">
    <ignored/>
  </testcase> <!-- testGetCallWithInvalidUrl -->
</testsuite>
